#!/bin/sh

if [ ! -d /tmp/CheckUser ]
 then
  mkdir /tmp/CheckUser
fi


Zahir=Away
Farhanah=Away

macadresser=`wl -i eth1 assoclist`
antal=0
antal=`qcsapi_sockrpc get_count_assoc wifi0`

while [ $antal -gt 0 ]
do
  antal=`expr $antal - 1`
  macadresser="`qcsapi_sockrpc get_station_mac_addr wifi0 $antal`;$macadresser"
done

case "$macadresser" in
 *CC:C0:79:FE:2F:96*)
 Zahir=Home
 ;;
esac

case "$macadresser" in
 *A0:CC:2B:14:0E:57*)
 Farhanah=Home
 ;;
esac

if [ "$Zahir" = Home ]
then
 if [ ! -f /tmp/CheckUser/ZahirHome ]
 then
  touch /tmp/CheckUser/ZahirHome
  curl "https://graph-na02-useast1.api.smartthings.com/api/smartapps/installations/e9aeb481-42e1-4161-9ba7-5c976e3809fc/Phone/home?access_token=d6fa95f2-77ca-4f65-b972-3ca068d20a3a" -k
 fi
else
 if [ -f /tmp/CheckUser/ZahirHome ]
 then
  rm -f /tmp/CheckUser/ZahirHome
  curl "https://graph-na02-useast1.api.smartthings.com/api/smartapps/installations/e9aeb481-42e1-4161-9ba7-5c976e3809fc/Phone/away?access_token=d6fa95f2-77ca-4f65-b972-3ca068d20a3a" -k
  fi
fi

if [ "$Farhanah" = Home ]
then
 if [ ! -f /tmp/CheckUser/FarhanahHome ]
 then
  touch /tmp/CheckUser/FarhanahHome  
 fi
else
 if [ -f /tmp/CheckUser/FarhanahHome ]
 then
  rm -f /tmp/CheckUser/FarhanahHome
 fi
fi
